config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/authentications/omniauth_callbacks", :sessions => "users/sessions"}
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  namespace :mood do
    get :selection
    post :suggestion
    get :suggestion, to: redirect("/mood/selection")
  end

  resources :meals, :only => [:index, :new, :create]
  resources :users, :only => [:new]

  root to: "pages#index"
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/authentication.rb
class Authentication < ActiveRecord::Base

  belongs_to :user

  def self.user_from_omniauth(auth, options = {})
    if authentication = where(provider: auth.provider, uid: auth.uid).first
      authentication.user.meals.create(choice_id: options[:last_choice_id]) if options[:last_choice_id]
      authentication.user
    else
      User.create do |user|
        user.email = auth.info.email
        user.name = auth.info.name
        user.password = Devise.friendly_token[0,20]
        user.authentications_attributes = [{ provider: auth.provider, uid: auth.uid }]
        user.meals_attributes = [{ choice_id: options[:last_choice_id] }] if options[:last_choice_id]
      end
    end
  end

end

app/models/choice.rb
class Choice < ActiveRecord::Base
  has_many :taggings
  has_many :tags, through: :taggings

  validates :name, presence: true, uniqueness: { scope: :user_id, message: "already exists" }
  validates_associated :tags

  def picture_url
    name.gsub(" ", "-")
  end

end

app/models/meal.rb
class Meal < ActiveRecord::Base

  belongs_to :user
  belongs_to :choice

  before_save :guess_occasion

  private

  def guess_occasion
    self.occasion = Occasion.guess unless self.occasion
  end

end

app/models/metrics.rb
class Metrics

  def self.most_frequent_tags_for(user)
    Tag.select("tags.id, tags.name, count(tags.id) as tag_count").joins(:choices).where(:"choices.id" => user.meals.pluck(:choice_id)).group("tags.name, tags.id").order("3 desc")
  end

  def self.most_frequent_tags_data(user)
    tags = self.most_frequent_tags_for(user).limit(10)
    data = tags.map {|t| [t.name.capitalize, t.tag_count]}
    data = [["Selection", "Count"]] + data
  end

end

app/models/mood.rb
class Mood

  def self.next_tags(previous_tags = [])
    chosen_tag_ids = Tagging.select("tag_id").all.uniq
    tags = Tag.where(id: chosen_tag_ids).where.not(name: previous_tags)
    tags.sample(10)
  end

  def self.suggest(selections, offset = 0)
    return shuffle if selections.blank?
    choices = Choice.select("choices.id, choices.name, count(tags.id)").
                      joins(:tags).
                      where(:"tags.name" => selections).
                      group("choices.id,choices.name").
                      order("3 desc")
    # Search most matched choice
    choices.blank? ? shuffle : choices[offset % choices.length]
  end

  private

    def self.shuffle
      Choice.where(nil).sample(1).first
    end

end

app/models/occasion.rb
class Occasion

  DEFAULT_OCCASIONS = {
    breakfast: (5...11),
    lunch: (11...16)
  }

  def self.guess(time = Time.now, ranges = DEFAULT_OCCASIONS, default_occasion = 'dinner')
    value = ranges.select{|key, value| value.include_with_range?(time.hour)}
    value.blank? ? default_occasion : value.keys.first.to_s
  end

end

app/models/setting.rb
class Setting < ActiveRecord::Base
  validate :name, uniqueness: true, presence: true
  validate :value, presence: true
  validate :data_type, presence: true

  def self.get(setting_name)
    setting = Setting.where(name: setting_name).first
    setting && setting.value.send(setting.data_type)
  end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :taggings
  has_many :choices, through: :taggings

  validates :name, presence: true, uniqueness: true
  validates_associated :choices

  def as_json(options={})
    {:name => name, :picture => picture_url}
  end

end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :tag
  belongs_to :choice

  validates :tag_id, presence: true, uniqueness: { scope: :choice_id, message: "already exists" }
  validates :choice_id, presence: true, uniqueness: { scope: :tag_id, message: "already exists" }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  devise :omniauthable, :omniauth_providers => [:facebook]

  has_many :authentications
  has_many :meals

  accepts_nested_attributes_for :authentications, :meals
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    admin_root_path and return if resource.is_a? AdminUser
    meals_path

  end
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController

  before_action :choice, :only => [:create]
  before_action :authenticate_user!, :only => [:index, :create]

  def index
    @meals = current_user.meals.includes(:choice).order("created_at desc")
    @metric_data = Metrics.most_frequent_tags_data(current_user)
  end

  def new
    @choices = Choice.all.map { |choice| choice.name.titleize }

  end

  def create
    if @meal = current_user.meals.create(choice: choice, occasion: params[:occasion])
      flash[:success] = "Bon appetit!"
      redirect_to meals_path
    else
      flash[:error] = @meal.errors.full_messages.to_sentence
      render :new
    end
  end
  
  private

  def choice
    @choice ||= begin
                  choice = Choice.find_by!(name: params[:choice].downcase)
                  session[:last_choice_id] = choice.id
                  choice
                end
  end

end

app/controllers/mood/tags_controller.rb
class Mood::TagsController < ApplicationController

  def index
    respond_to do |format|
      format.html do
        @tags = Mood.next_tags
        session[:tags] = @tags.to_json
      end

      format.js do
        previous_tags = session[:tags].blank? ? [] : JSON.parse(session[:tags])
        @tags = Mood.next_tags(previous_tags)
        session[:tags] = (@tags + previous_tags).to_json
        render json: @tags.to_json, layout: false
      end
    end
  end

end

app/controllers/mood_controller.rb
class MoodController < ApplicationController

  def selection
    respond_to do |format|
      format.html do
        @tags = Mood.next_tags
        p @tags
        session[:tags] = @tags.map(&:name).to_json
      end

      format.js do
        previous_tags = session[:tags].blank? ? [] : JSON.parse(session[:tags])
        @tags = Mood.next_tags(previous_tags)
        session[:tags] = (@tags.map(&:name) + previous_tags).to_json
        render json: @tags.to_json, layout: false
      end

    end
  end

  def suggestion
    set_offset
    @selections = params[:selections]
    @suggestion = Mood.suggest(@selections, @offset)
    @offset += 1
  end

  private

  def set_offset
    @offset ||= params[:offset].to_i
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    render layout: 'landing'
  end
end

app/controllers/users/authentications/omniauth_callbacks_controller.rb
class Users::Authentications::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = Authentication.user_from_omniauth(request.env["omniauth.auth"], last_choice_id: session[:last_choice_id])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end


end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController

  before_action :choice

  def new
  end


  private

  def choice
    @choice ||= Choice.find_by(id: session[:last_choice_id]) if session[:last_choice_id]
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!! 5
%html.no-js{:lang => "en"}

  = render :partial => "shared/head"

  %body{class: "#{'dashboard' if user_signed_in?}"}
    .main-wrapper
      = render :partial => "shared/header"

      - if user_signed_in?
        %nav.main-nav
          .wrapper
            %ul
              %li
                = link_to "Dashboard", meals_path
              %li
                = link_to "Mood Test", mood_selection_path
              %li
                = link_to "Log out", "/users/sign_out"

      .main-content
        = yield

    = render :partial => "shared/footer"
    
    = render :partial => "shared/scripts"

app/views/layouts/dashboard.html.haml
!!! 5
%html.no-js{:lang => "en"}

  = render :partial => "shared/head"

  %body.dashboard
    .main-wrapper
      = render :partial => "shared/header"

      %nav.main-nav
        .wrapper
          %ul
            %li
              = link_to "Dashboard", meals_path
            %li
              = link_to "Mood Test", mood_selection_path
            %li
              = link_to "Log out", "/users/sign_out"

      .main-content
        = yield

    = render :partial => "shared/footer"
    
    = render :partial => "shared/scripts"

app/views/layouts/landing.html.haml
!!! 5
%html.no-js{:lang => "en"}

  = render :partial => "shared/head"

  %body.landing
    .main-wrapper
      = render :partial => "shared/header"

      .main-content
        = yield
    
    = render :partial => "shared/scripts"

app/views/meals/index.html.haml
.wrapper
  %h1.heading--jumbo= "Welcome, #{current_user.name}"
  
  .grid
    .grid__item.one-whole.desk-two-thirds.push--bottom>
      %h2.heading--large.text--left.push-half--bottom What you've been eating

      %ul.list--table
        - @meals.each do |meal|
          %li.choice-entry{class: "choice-entry__occasion--#{meal.occasion}"}
            .choice-entry__image
              = image_tag "suggestions/#{meal.choice.picture_url}.jpg", alt: meal.choice.name.capitalize
            .choice-entry__body
              .choice-entry__text-container
                .choice-entry__text
                  You had
                  %strong= meal.choice.name.capitalize 
                  for 
                  %strong= meal.occasion.capitalize
                  = "#{time_ago_in_words(meal.created_at)} ago"
    .grid__item.one-whole.desk-one-third>
      %h2.heading--large.text--left.push-half--bottom What you usually choose
      #donutchart

- content_for :javascript do
  = javascript_include_tag "https://www.google.com/jsapi"
  :javascript
    google.load("visualization", "1", {packages:["corechart"]});
    google.setOnLoadCallback(drawChart);
    function drawChart() {
      var data = google.visualization.arrayToDataTable(#{@metric_data});

      var options = {
        title: '',
        legend: 'bottom',
        'chartArea': {'width': '100%', 'height': '80%'},
        height: 300
      };

      var chart = new google.visualization.PieChart(document.getElementById('donutchart'));
      chart.draw(data, options);
    }

app/views/meals/new.html.haml
- content_for :title do
  What are you eating? - Cravings

.wrapper
  %h1.heading--jumbo What are you eating?

  = form_tag meals_path do
    .form-field.autocomplete-container.js-autocomplete-container.float--left
      %label.label--inline I'm eating...
      = text_field_tag "choice", "", placeholder: "i.e. Pizza", class: "text-input", required: true

    .form-field.clear
      %label.label ..for..
      .grid--full
        %label.custom-input.grid__item.one-third>
          = radio_button_tag "occasion", "breakfast"
          %span.custom-input__skin.input-skin--choice.input-choice--first
            %i.icon.icon--breakfast
            %span.custom-input__label Breakfast
        %label.custom-input.grid__item.one-third>
          = radio_button_tag "occasion", "lunch"
          %span.custom-input__skin.input-skin--choice
            %i.icon.icon--lunch
            %span.custom-input__label Lunch
        %label.custom-input.grid__item.one-third>
          = radio_button_tag "occasion", "dinner"
          %span.custom-input__skin.input-skin--choice.input-choice--last
            %i.icon.icon--dinner
            %span.custom-input__label Dinner

    .text--center
      = submit_tag "Save it!", class: "button button--primary button--huge button--mobile"

      - content_for :javascript do
        = javascript_include_tag "//code.jquery.com/ui/1.11.2/jquery-ui.js"
        :javascript
          $(function() {
            var availableTags = #{@choices.to_json};
            $("#choice").autocomplete({
              delay: 0,
              minLength: 0,
              autoFocus: true,
              source: availableTags,
              appendTo: ".js-autocomplete-container",
              change: function (event, ui) { if(!ui.item) { $(event.target).val(""); } }
            }).focus(function() {
              $(this).autocomplete("search");
            }).click(function() {
              $(this).autocomplete("search");
            }).parents("form").keypress(function(e) {
              if (e.keyCode == 13) {               
                e.preventDefault();
                return false;
              }
            });
          });

app/views/mood/selection.html.haml
- content_for :title do
  What are you in the mood to eat? - Cravings

.wrapper
  %h1.heading--jumbo Are you in the mood for...

  .choices-container
    .choices
      %button.choice.js-choice#js-left-choice
        %span.choice__icon
          %i.icon
        %span.choice__name.js-choice-name
      .choices__divider>
        or
      %button.choice.js-choice#js-right-choice
        %span.choice__icon
          %i.icon
        %span.choice__name.js-choice-name
    %button.choices__neither.has-border.js-choice
      Neither!

  .grid--rev.choices__footer
    .grid__item.one-whole.lap-and-up-one-half.choices__chosen>
      .js-selected-tags.js-hidden
        %p.push-half--bottom You are in the mood for:
        %ul.list--tags
    .grid__item.one-whole.lap-and-up-one-half>
      = link_to "I've already decided what I'm eating!", new_meal_path, class: "text--skip"

- content_for :javascript do
  :javascript
    FormAuthenticityToken = "#{form_authenticity_token}";
    Cravings.Mood.maxSelections = #{Setting.get("max_selections")};
    Cravings.Mood.Tags = #{@tags.to_json};

  = javascript_include_tag "mood/selection"

app/views/mood/suggestion.html.haml
- content_for :title do
  What are you in the mood to eat? - Cravings

.wrapper
  %h1.heading--jumbo Are you in the mood for...

  .choices-container--suggestion
    %button.choice--suggestion.js-select-choice
      .suggestion__image
        = image_tag "suggestions/#{@suggestion.picture_url}.jpg", alt: @suggestion.name.capitalize
        .suggestion__name
          = @suggestion.name.capitalize

  .grid--rev.grid--full.push-double--bottom
    .grid__item.one-whole.lap-and-up-one-half>
      %button.suggestion__text.js-select-choice Yup! I'm eating this 

    .grid__item.one-whole.lap-and-up-one-half.js-other-choice>
      %button.choices__neither Nah... What else you got?

  .text--center
    = link_to "I've already decided what I'm eating!", new_meal_path, class: "text--skip"

= form_tag "/mood/suggestion", method: :post, class: "js-mood-selections" do
  %input(type="hidden" name="offset" value="#{@offset}")
  - params[:selections].each do |selection_name|
    %input(type="hidden" name="selections[]" value="#{selection_name}")

= form_tag "/meals", method: :post, class: "js-mood-suggestion" do
  %input(type="hidden" name="choice" value="#{@suggestion.name}")

- content_for :javascript do
  :javascript
    Cravings.Mood.Selections = #{@selections.to_json};

  = javascript_include_tag "mood/suggestion"

app/views/mood/tags/index.html.haml
= content_for :javascript do
  = javascript_include_tag "mood/tags/index"
  :javascript
    Cravings.Mood.Tags = #{@tags.to_json}

app/views/pages/index.html.haml
- content_for :title do
  Cravings

.wrapper
  .text--center
    %h1.heading--jumbo.push-half--bottom Don't know what to eat?
    %p Let's find out what you are craving for
    = link_to "Let's Go!", mood_selection_path, class: "button button--brand button--huge push--bottom"
    .push-double--bottom
      = link_to "Go to my dashboard", user_omniauth_authorize_path(:facebook), class: "text--skip"

    .push-half--bottom
      %strong Remember to vote for us!
    %p
      = link_to "http://railsrumble.com/entries/203-incognito-mode", target: "_blank" do
        = image_tag "https://d4nnn7wspfa3h.cloudfront.net/rails-rumble-badge-2014.png", alt: "Vote for Cravings for the RailsRumble 2014"

app/views/shared/_footer.html.haml
%footer.main-footer
  .push-half--bottom
    %strong Remember to vote for us!
  %p
    = link_to "http://railsrumble.com/entries/203-incognito-mode", target: "_blank" do
      = image_tag "https://d4nnn7wspfa3h.cloudfront.net/rails-rumble-badge-2014.png", alt: "Vote for Cravings for the RailsRumble 2014", width: 135, height: 52

app/views/shared/_head.html.haml
%head
  %meta{:charset => "utf-8"}
  /[if IE]
  %meta{:content => "IE=edge,chrome=1", "http-equiv" => "X-UA-Compatible"}
  %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
  %title= yield :title
  %link{:href => "#{image_path 'favicon.png'}", :rel => "shortcut icon"}
  %link{:href => "#{image_path 'apple-touch-icon.png'}", :rel => "apple-touch-icon"}

  = javascript_include_tag "modernizr"
  = stylesheet_link_tag "application", :media => "all"
  = csrf_meta_tags
  

app/views/shared/_header.html.haml
%header.main-header
  .wrapper
    .main-logo
      = link_to "Cravings", "/"

app/views/shared/_scripts.html.haml
= javascript_include_tag "application"
/[if (gte IE 6)&(lte IE 8)]
  %script{:src => "/assets/selectivizr.js"}
  
= yield :javascript

:javascript
  var _swell_site_ids = _swell_site_ids || [];
  _swell_site_ids.push('85ec1a21');
  (function() {
    var s = document.createElement('script');
    s.type = 'text/javascript';
    s.async = true;
    s.src = '//df50assd5876f.cloudfront.net/hello.js';
    ( document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0] ).appendChild( s );
  })();